working version with new agreement types
JPasniczek/rizzSim pull request #7
Opened 2024-08-07 20:32 UTC by altarluser

2024-08-07 20:56 UTC, imgeyuez commented
Checked the PR and looks finee to me

2024-08-07 20:58 UTC, imgeyuez approved these changes
just a small typo in the prompt, otherwise looks good to mee

2024-08-07 21:14 UTC, JPasniczek requested changes
After all amazing job, two absolutely cosmetic changes found, apart from that zucchini :3

2024-08-07 21:14 UTC, JPasniczek commented on games/datingsim/resources/initial_prompts/initialprompt_playerA.template
>  Start the game with the reason, your sentiment and the opening phrase.
Just a tiny add of endline here (add an enter to the end of the file coz otherwise github cries)

2024-08-07 21:14 UTC, JPasniczek commented on games/datingsim/resources/initial_prompts/initialprompt_playerA.template
> +There are four types of agreement: "Agreement on Time", "Agreement on Location", "Agreement on Action", "Overall Agreement". You and the other player needs to find an agreement on each of these types
need instead of needs, an absolutely cosmetic change

2024-08-08 11:06 UTC, JPasniczek approved these changes
Thank you for making the tiny adjustments, ready to merge :)

2024-08-08 11:13 UTC, merged